### ISSUE TITLE
Combine observables to create another observable

### ISSUE THREAD

**Issue by danielgomezrico** [ReactiveX/RxJavaJoins#8]
I´m using plan to do it

```
        Observable<Track> trackObservable = Track.get(pickLocation, dropLocation);
        Observable<UploadedFile> uploadedFileObservable = uploadImage(bitmapPath);
        Observable<OrderData> orderDataObservable = Observable.just(order);
        Observable<Address> pickObservable = Address.get(order.getPickAddress());
        Observable<Address> dropObservable = Address.get(order.getDropAddress());

Plan0<Observable<Order>> plan = JoinObservable.from(pickObservable)
                .and(dropObservable)
                .and(trackObservable)
                .and(uploadedFileObservable)
                .and(orderDataObservable)
                .then(Order::create);

        return JoinObservable.when(plan).toObservable().flatMap(orderObservable -> orderObservable);

...

private static Observable<Order> create(Address pickAddress, Address dropAddress, Track track,
                                            UploadedFile image, OrderData orderData) {
       ...

        return SERVICE.createOrder(newOrder)
                .map(order -> {
                    save(order);
                    return order;
                });
    }
```

I do `toObservable().flatMap(orderObservable -> orderObservable);` becuase createOrder generates an observable then `.then(Order::create);` creates an `Observer<Observer<Order>>`.

But don´t work.
I can´t find a way to chain multiple observers results into another observer :(

**Comment by akarnokd** [comment]
Sorry for answering this late. I don't particularly use this library and I don't have a "feel" for its use either (even though I ported from Rx.NET). Could you try and use standard RxJava operators, such as `zip` and `combineLatest` instead?

**Comment by danielgomezrico** [comment]
I end up doing this as a suggestion https://gist.github.com/dlew/c824beaeb967fa3c096e from dlew.
but looks weird `observable -> observable`.

**Comment by akarnokd** [comment]
Fun fact: that is the fluent version of a `merge(Observable<Observable<T>>)`.

I'm glad it worked out for you.
